language: go

go:
  - 1.5
  - tip

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - go get github.com/constabulary/gb/...
  - go get github.com/jteeuwen/go-bindata/...

script:
  - gb vendor restore
  - make bindata
  - make release
