CSS      = reveal.js/css/...
JS       = reveal.js/js/...
LIB      = reveal.js/lib/...
PLUGIN   = reveal.js/plugin/...
TEMPLATE = templates/...

bindata: assets.go
	$(GOPATH)/bin/go-bindata -o=assets.go $(CSS) $(JS) $(LIB) $(PLUGIN) $(TEMPLATE)
