CSS      = reveal.js/css/...
JS       = reveal.js/js/...
LIB      = reveal.js/lib/...
PLUGIN   = reveal.js/plugin/...
THEMES	 = themes/...
ASSETS	 = assets/...

bindata:
	$(GOPATH)/bin/go-bindata -o=src/github.com/nautsio/presenter/assets.go $(CSS) $(JS) $(LIB) $(PLUGIN) $(THEMES) $(ASSETS)

osx:
	gb build all

linux:
	GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -o $(GOPATH)/bin/presenter.linux .

windows:
	GOOS=windows GOARCH=386 go build -o $(GOPATH)/bin/presenter.exe .
